# Generated by Django 3.2.7 on 2021-10-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='captain',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='flights',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='flights',
            name='departure',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='flights',
            name='destination',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='flights',
            name='notes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
