# Generated by Django 3.2.7 on 2021-10-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20211004_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='aircraft',
            field=models.CharField(choices=[('B744', 'Boeing 747'), ('E190', 'Embraer 190'), ('E170', 'Embraer 170'), ('S2000', 'Saab 2000'), ('J41', 'BAE Jetstream 41')], default='B744', max_length=16),
        ),
    ]
