# Generated by Django 3.2.7 on 2021-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_alter_flights_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='duration',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=4),
        ),
    ]
