# Generated by Django 3.2.8 on 2021-10-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0007_flights_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.CharField(default='', max_length=25)),
                ('departure', models.CharField(default='', max_length=5)),
                ('destination', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
