# Generated by Django 3.2.8 on 2021-10-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0008_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
