# Generated by Django 3.2.7 on 2021-10-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_auto_20211009_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='captain',
            field=models.CharField(default='', max_length=25),
        ),
    ]
