# Generated by Django 3.2.7 on 2021-10-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0010_alter_flights_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
