# Generated by Django 3.2.7 on 2021-10-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0012_alter_flights_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
