# Generated by Django 3.2.7 on 2021-10-11 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0009_delete_mymodel'),
        ('logbook', '0013_alter_flights_notes'),
    ]

    operations = [
    ]
