# Generated by Django 3.2.7 on 2021-10-11 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbook', '0014_merge_0009_delete_mymodel_0013_alter_flights_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft', models.CharField(choices=[('PA-28', 'Piper Warrier'), ('C150', 'Cessna 150'), ('Cub', 'Piper Cub')], default='PA-28', max_length=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
