# Generated by Django 3.2.7 on 2021-10-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0016_auto_20211011_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=False, max_length=50),
        ),
    ]
